---
- name: 'Start Sphinx search container'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Start container'
      when: ENABLE_SPHINXSEARCH == true
      docker_container:
        name: "{{DOCKER_PREFIX}}_sphinxsearch"
        image: "sphinxsearch:latest"
        state: started
        restart_policy: "{{ RESTART_POLICY }}"
        volumes:
        - "{{ DATA_PATH_HOST }}/sphinxsearch:/var/lib/sphinx/data"
        - "./../../../services/sphinxsearch/sphinx.conf:/etc/sphinx/sphinx.conf"
        ports:
        - "9312:9312"
        - "9306:9306"
        log_driver: "json-file"
        log_options:
          "max-size": "100m"
          "max-file": "3"
        networks:
          - name: "{{DOCKER_PREFIX}}_backend"