---
- name: 'Start MySQL docker container'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Start container'
      when: DATABASE_TYPE == 'mysql'
      docker_container:
        name: "{{DOCKER_PREFIX}}_mysql"
        image: "mysql:{{MYSQL_VERSION}}"
        state: started
        restart_policy: "{{ RESTART_POLICY }}"
        log_driver: "json-file"
        log_options:
          "max-size": "100m"
          "max-file": "3"
        env:
          MYSQL_DATABASE: "{{DATABASE_NAME}}"
          MYSQL_USER: "{{DATABASE_USER}}"
          MYSQL_PASSWORD: "{{DATABASE_PASSWORD}}"
          MYSQL_ROOT_PASSWORD: "{{DATABASE_ROOT_PASSWORD}}"
          TZ: "{{WORKSPACE_TIMEZONE}}"
        volumes:
        - "{{ DATA_PATH_HOST }}/mysql:/var/lib/mysql"
        - "./../../../services/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        ports:
        - "{{ DATABASE_PORT }}:3306"
        networks:
          - name: "{{DOCKER_PREFIX}}_backend"
#- name: 'Connect to docker workspace and apply migrations'
#  hosts: laradockoctober_workspace_1
#  remote_user: laradock
#  tasks:
#    - name: 'Include global vars'
#      include_vars:
#        dir: ./../../vars/global
#    - name: 'Include environment vars'
#      include_vars:
#        dir: ./../../vars/{{ env }}
#    - name: Create script file
#      copy:
#        content: "GRANT ALL ON `{{ DATABASE_NAME }}`.* TO '{{ DATABASE_USER }}'@'%';"
#        dest: "command-script.sql"
#    - name: Run script
#      raw: "/usr/bin/mysql -h{{DOCKER_PREFIX}}_mysql -uroot --password={{DATABASE_ROOT_PASSWORD}} < command-script.sql"
#    - name: Remove script file
#      file:
#        path: "command-script.sql"
#        state: absent